# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '3.0.100-preview5-011568'

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: src/Blazor.IntersectionObserver.JS

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: run test
      workingDir: src/Blazor.IntersectionObserver.JS

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/junit.xml'
      workingDir: src/Blazor.IntersectionObserver.JS

  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
      workingDir: src/Blazor.IntersectionObserver.JS

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: 'src/Blazor.IntersectionObserver/*.csproj'
      configuration: '$(buildConfiguration)'
      versioningScheme: byPrereleaseNumber
      majorVersion: '0'
      minorVersion: '1'
      patchVersion: '0'


