name: release

on:
    push:
        branches: [master]
        paths-ignore:
            - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 10.x

      - name: Install npm dependencies
        run: |
            npm ci
        working-directory: src/Ljbc1994.Blazor.IntersectionObserver

      - name: Run tests
        run: |
            npm run test
        working-directory: src/Ljbc1994.Blazor.IntersectionObserver

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true
      
      - name: Dotnet build
        run: dotnet build --configuration Release

      - name: Dotnet pack
        run: dotnet pack src/Ljbc1994.Blazor.IntersectionObserver/*.csproj --configuration Release --verbosity Detailed
      
      - name: Dotnet publish to nuget
        run: dotnet nuget push src/Ljbc1994.Blazor.IntersectionObserver/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      
      